<a href="https://colab.research.google.com/github/valerojuan18/pythonForDataScience/blob/main/Pandas_I_O.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Leyendo archivos CSV**

### **Importando archivo CSV**

In [51]:
import pandas as pd

In [52]:
datos = pd.read_csv('/content/superstore_data.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/superstore_data.csv'

In [53]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tama침o_familia,Categoria_de_renta,Ocupacion,A침os_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [54]:
datos_punto_coma = pd.read_csv('/content/superstore_data_punto_coma.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/superstore_data_punto_coma.csv'

In [55]:
datos_punto_coma.head()

NameError: name 'datos_punto_coma' is not defined

In [ ]:
## El df no muestra ningun dato debido a que el archivo que se est치 subiendo es de tipo csv (valor separado por coma)
# Soluci칩n...

### **Par치metros de la funci칩n read_csv**
Documentaci칩n: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv

In [ ]:
# Par치metro sep
datos_punto_coma = pd.read_csv('/content/superstore_data_punto_coma.csv', sep=';')

In [56]:
datos_punto_coma.head()

NameError: name 'datos_punto_coma' is not defined

In [ ]:
# Par치metro nrows
datos_primeras_lineas = pd.read_csv('superstore_data.csv', nrows=5)

In [57]:
datos_primeras_lineas

NameError: name 'datos_primeras_lineas' is not defined

In [58]:
# Par치metro usecols
datos_seleccion = pd.read_csv('superstore_data.csv', usecols=['Id', 'Year_Birth', 'Income'])
datos_seleccion

FileNotFoundError: [Errno 2] No such file or directory: 'superstore_data.csv'

In [59]:
# Como alternativa, se pueden colocar solo las posiciones de los registros en el par치metro
datos_seleccion = pd.read_csv('superstore_data.csv', usecols=[0, 1, 4])
datos_seleccion

FileNotFoundError: [Errno 2] No such file or directory: 'superstore_data.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
datos_seleccion.to_csv('clientes_mercado.csv')

In [60]:
clientes_mercado = pd.read_csv('clientes_mercado.csv')
clientes_mercado

FileNotFoundError: [Errno 2] No such file or directory: 'clientes_mercado.csv'

In [ ]:
datos_seleccion.to_csv('datos_mercado.csv', index=False)

In [ ]:
datos_mercado = pd.read_csv('datos_mercado.csv')
datos_mercado

## **Leyendo Archivos excel**

### **Importando archivos excel**

In [ ]:
import pandas as pd

In [ ]:
archivo = 'emisiones_CO2.xlsx'

In [ ]:
datos_CO2 = pd.read_excel(archivo)
datos_CO2

In [ ]:
pd.ExcelFile(archivo).sheet_names

### **Par치metros de la funci칩n read_excel**
Documentaci칩n: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html#pandas.read_excel

In [ ]:
percapita = pd.read_excel(archivo, sheet_name='emisiones_percapita')

In [ ]:
percapita.sample(5)

In [ ]:
fuentes = pd.read_excel(archivo, sheet_name='fuentes')

In [ ]:
fuentes.tail()

In [ ]:
intervalo = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols='A:D')

In [ ]:
intervalo

In [ ]:
intervalo_2 = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols='A:D', nrows=10)

In [61]:
intervalo_2

NameError: name 'intervalo_2' is not defined

### **Escribiendo archivos excel**

In [ ]:
intervalo.to_excel('co2_percapita.xlsx', index = False)

In [ ]:
pd.read_excel('co2_percapita.xlsx')

### **Leyendo datos de google sheet**

link: https://docs.google.com/spreadsheets/d/1iZMgTAO0oUZ1VFq61awZNRjQNOfXF-Q4g4s3dAJvS3Q/edit?gid=372212640#gid=372212640

In [ ]:
sheet_id = '1iZMgTAO0oUZ1VFq61awZNRjQNOfXF-Q4g4s3dAJvS3Q'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
datos_co2_sheets = pd.read_csv(url)
datos_co2_sheets

In [ ]:
# Para leer una hoja del libro en concreto, se hace lo siguiente...
sheet_id = '1iZMgTAO0oUZ1VFq61awZNRjQNOfXF-Q4g4s3dAJvS3Q'
sheet_name = 'emisiones_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
percapita_sheets = pd.read_csv(url_percapita)
percapita_sheets

In [ ]:
sheet_id = '1iZMgTAO0oUZ1VFq61awZNRjQNOfXF-Q4g4s3dAJvS3Q'
sheet_name = 'fuentes'
url_fuentes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
fuentes_sheets = pd.read_csv(url_fuentes)
fuentes_sheets.head()

## **Leyendo archivos JSON**

### **Importando archivos JSON**

In [ ]:
import pandas as pd

In [ ]:
archivo_json = 'pacientes.json'
datos_pacientes = pd.read_json(archivo_json)
datos_pacientes

In [ ]:
datos_pacientes.shape

In [ ]:
archivo_json_2 = 'pacientes_2.json'
datos_pacientes_2 = pd.read_json(archivo_json_2)
datos_pacientes_2

### **Normalizando archivos JSON**

In [62]:
df_normalizado = pd.json_normalize(datos_pacientes_2['Pacientes'])
df_normalizado

NameError: name 'datos_pacientes_2' is not defined

### **Escribiendo archivos JSON**

In [ ]:
df_normalizado.to_json('historico_pacientes_norm.json')

In [63]:
pd.read_json('historico_pacientes_norm.json')

FileNotFoundError: File historico_pacientes_norm.json does not exist

## **Leyendo archivos HTML**

### **Importando p치ginas web**

In [ ]:
import pandas as pd

In [ ]:
datos_html = pd.read_html('peliculas_wikipedia.html')
datos_html

In [64]:
type(datos_html)

NameError: name 'datos_html' is not defined

In [ ]:
len(datos_html)

In [ ]:
top_peliculas = datos_html[1]
top_peliculas

### **Escribiendo archivos HTML**

In [ ]:
top_peliculas.to_html('top_peliculas.html', index = False)

In [ ]:
pd.read_html('top_peliculas.html')

In [65]:
top_peliculas.to_csv('top_peliculas_1998.csv', index=False)

NameError: name 'top_peliculas' is not defined

In [ ]:
datos = pd.read_csv('top_peliculas_1998.csv')
datos

## **Leyendo/escribiendo archivos XML**

In [ ]:
import pandas as pd

In [66]:
datos_imdb = pd.read_xml('imdb_top_1000.xml')
datos_imdb.head(3)

<ipython-input-66-c9cd640314e8>:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  datos_imdb = pd.read_xml('imdb_top_1000.xml')

XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

In [ ]:
datos_imdb.to_xml('Peliculas_imdb.xml', index = False)

## **Leyendo banco de datos**

In [67]:
import sqlalchemy

In [68]:
from sqlalchemy import create_engine, MetaData, table, inspect, text

In [69]:
engine = create_engine('sqlite:///memory:')

In [70]:
import pandas as pd

In [71]:
archivo = 'clientes_banco.csv'

In [72]:
datos = pd.read_csv(archivo)

In [73]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tama침o_familia,Categoria_de_renta,Ocupacion,A침os_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [74]:
datos.to_sql('clientes', engine, index=False)

ValueError: Table 'clientes' already exists.

In [75]:
inspector = inspect(engine)

In [76]:
print(inspector.get_table_names())

['clientes', 'empleados']

### **Leyendo una consulta SQL**

In [77]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [78]:
empleados = pd.read_sql(sql=text(query), con = engine.connect())

In [79]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tama침o_familia,Categoria_de_renta,Ocupacion,A침os_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcci칩n Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcci칩n Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [80]:
empleados.to_sql('empleados', con = engine.connect(), index=False)

ValueError: Table 'empleados' already exists.

In [81]:
pd.read_sql_table('empleados', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tama침o_familia,Categoria_de_renta,Ocupacion,A침os_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcci칩n Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcci칩n Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [82]:
pd.read_sql_table('empleados', con = engine.connect(), columns=['ID_Cliente', 'Grado_estudio', 'Rendimiento_anual'])

        ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

### **Actualizando una base de datos**

In [83]:
query = 'SELECT * FROM clientes'

In [84]:
pd.read_sql(sql=text(query), con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tama침o_familia,Categoria_de_renta,Ocupacion,A침os_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcci칩n Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [85]:
# Borrando registros
from sqlalchemy.exc import SQLAlchemyError
query = "DELETE FROM clientes WHERE ID_Cliente=5008804"
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ", r_set.rowcount)

(sqlite3.OperationalError) database is locked
[SQL: DELETE FROM clientes WHERE ID_Cliente=5008804]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [86]:
pd.read_sql_table('clientes', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tama침o_familia,Categoria_de_renta,Ocupacion,A침os_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcci칩n Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [87]:
# Actualizando registros
query = "UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente=5008808"
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ", r_set.rowcount)

(sqlite3.OperationalError) database is locked
[SQL: UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente=5008808]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [88]:
pd.read_sql_table('clientes', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tama침o_familia,Categoria_de_renta,Ocupacion,A침os_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relaci칩n-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcci칩n Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [89]:
inspector = inspect(engine)

In [91]:
print(inspector.get_table_names())

['clientes', 'empleados']